language: php
php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - phpunit --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
