language: php
php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) 
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml