language: php
php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml --coverage-html build/coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) 
  - wget http://www.molengo.com/app.phar
  - php app.phar upload